#include <stdio.h>

/*
    CS 361 HW2 instructions:
    - Display a command prompt and read in a command line from the user
    - Parse the command line into arguments, creating an array of character pointers, where array[0] points to the actual command and rest of the array elements point to the arguments to the command (Similar to main()’s argv[])
    - Fork off a child and have the child load the requested program by passing the argument vector created in step 2 to exec() family of system calls. The parent should report the PID of the child before proceeding to the next step.
    - Wait for the child to complete executing and report why it ended (exited or uncaught signal) and its exit value if available.
    - Repeat for first step forever till user enters the command exit
    - Your shell should also support basic I/O redirection line the unix shell.
    - $ command > filename Redirects the output of command to filename. The existing contents of filename are overwritten.
    - $ command >> filename` Redirects the output of command to filename. The output from command is appendend to contents of filename. Existing contents are not overwritten.
    - $ command < filename Command reads its input from filename instead of from stdin.
    - Your shell should handle the following signals:
    - SIGINT - Generated by Ctrl-C. This signal allows a user to teminate a running program. Your shell should not exit when user presses Ctrl-C but simply report that SIGINT signal has been received by the shell.
    - SIGTSTP - Generated by Ctrl-Z. Your shell should not exit when user presses Ctrl-Z but simply report that SIGTSTP signal has been received by the shell.
    - The shell need not support background processes or running more than one child at a time.
*/
int main(int argc, char *argv[]) {

    while(1) {
    // display prompt

    // read in line of input

    // parse command

    // fork a child and exec() command

    // report result, repeat above

    }
    return 0;
}

// catch signals

